## PyTorch: Tensors

In [4]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import time

### Numpy vs Torch

In [5]:
n = np.linspace(0,1,5)
t = torch.linspace(0,1,5)
n, t

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000]))

In [6]:
n = np.arange(36).reshape(3,3,4)
t = torch.arange(36).reshape(3,3,4)
n, t

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],
 
        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]]]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]],
 
         [[24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35]]]))

### Broadcasting Rules

When operating on two arrays, NumPy operates element-wise from the right. Two dimensions are compatible whe they're equal or one of them is 1.

In [7]:
a = np.ones((6, 5)) #dim(a) = (6, 5)
b = np.arange(5).reshape((1, 5)) #dim(b) = (1, 5)
a + b, a * b

(array([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]]),
 array([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]]))

In [8]:
Scale = torch.tensor([0.5, 1.5 , 1])
Image = torch.randn((256, 256, 3))

In [9]:
Image*Scale

tensor([[[-0.1634,  2.1713, -1.1292],
         [-0.2007, -1.0559,  0.8080],
         [ 0.7907,  1.8973, -0.7830],
         ...,
         [ 1.0116, -0.0690, -0.5089],
         [ 0.3779,  1.1526, -0.6225],
         [ 0.1728, -0.5644,  0.9306]],

        [[-0.0120,  0.3001,  1.2713],
         [ 0.5120, -1.8691,  0.8941],
         [-0.2204,  1.2343, -0.7813],
         ...,
         [ 0.0714,  0.8257, -0.9739],
         [-0.3518, -0.8055, -0.1430],
         [-0.0250,  3.7371,  0.6299]],

        [[-0.4548, -2.0558,  0.2939],
         [-0.4581, -0.5241, -1.2545],
         [ 0.3052, -1.6021, -0.9727],
         ...,
         [ 0.2978,  0.4803,  0.0106],
         [-0.1763, -1.8088, -0.2131],
         [-0.2420, -0.6122,  0.1082]],

        ...,

        [[-0.3952, -0.0584,  0.4809],
         [-0.2726, -1.8083,  0.5468],
         [ 0.1329,  0.0296, -0.7861],
         ...,
         [ 1.1135,  0.5136, -0.6425],
         [ 0.1099, -0.8317, -0.9727],
         [ 0.1619, -0.8250, -1.1187]],

        [[

In [10]:
Image = torch.randn((2, 256, 256, 3))
Scale = torch.tensor([0.5, 1.5, 1, 1.5, 1, 0.5]).reshape((2, 1, 1, 3))

In [11]:
Image*Scale

tensor([[[[-1.6629e-01, -6.9128e-01, -5.0191e-01],
          [-3.1175e-02, -1.3800e-01, -6.1359e-01],
          [ 9.4043e-02, -2.0676e-01,  7.0954e-01],
          ...,
          [ 1.9291e-01,  1.9714e+00, -7.9921e-01],
          [-1.1566e-01,  4.1141e-01, -9.9923e-02],
          [ 8.6408e-02, -1.9453e-01,  1.7568e+00]],

         [[-4.6344e-01,  2.6441e-02, -1.0039e-01],
          [ 1.8243e-01,  5.0761e-02,  1.3067e+00],
          [ 3.4766e-01, -3.8414e-01,  7.2780e-01],
          ...,
          [ 3.0570e-01,  3.0132e+00,  8.2712e-01],
          [-8.7221e-01, -1.3217e-01,  4.1263e-01],
          [ 3.0316e-01, -1.2320e+00,  1.8330e+00]],

         [[ 3.9512e-01, -1.7645e+00, -1.9225e+00],
          [-1.0295e-01,  3.1303e+00,  9.6039e-01],
          [-7.9477e-01,  4.1056e+00, -3.4458e-01],
          ...,
          [ 8.6349e-02, -3.5881e-01,  1.8503e+00],
          [ 8.6052e-01, -1.7572e+00, -1.8108e-01],
          [-1.6112e-01, -2.0554e+00,  1.0546e+00]],

         ...,

         [[-6.62

### Operations over dimensions

In [12]:
t = torch.tensor([0.5, 1, 3, 4])
torch.mean(t), torch.std(t), torch.max(t), torch.min(t)

(tensor(2.1250), tensor(1.6520), tensor(4.), tensor(0.5000))

In [13]:
t = torch.arange(20, dtype=float).reshape(5, 4)
t, torch.mean(t, axis=0) #mean across the rows

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([ 8.,  9., 10., 11.], dtype=torch.float64))

In [14]:
t = torch.randn(2, 4, 4, 3)
#to take the mean across the batch (axis=0)
print(t)
torch.mean(t, axis=0).shape#, torch.mean(t, axis=0)

tensor([[[[ 3.0033,  2.7461, -0.1632],
          [ 0.2548,  0.9874, -1.0438],
          [-2.2540, -0.3068,  0.0418],
          [-1.2261,  0.4125, -0.7121]],

         [[-0.1110, -0.6103, -0.1660],
          [ 0.5552,  0.0794,  0.1621],
          [ 0.1069, -1.1227,  0.3217],
          [-0.2307,  0.8903, -0.3795]],

         [[ 1.1994,  1.4867, -0.4862],
          [ 1.1714,  0.9742, -1.2106],
          [ 0.8781,  1.3694,  2.0522],
          [ 1.0669,  0.8658,  0.3261]],

         [[ 0.7036,  0.1829, -0.4007],
          [-0.9376, -0.2886,  1.6389],
          [-1.0259, -0.3360,  0.4060],
          [-0.2921,  0.9432,  0.4077]]],


        [[[-0.8653,  0.8024,  0.7306],
          [-1.3010, -0.6427,  0.2586],
          [-1.3155,  0.8494,  0.6151],
          [-0.3393,  1.2909,  0.7958]],

         [[ 0.0095, -0.1855, -0.2000],
          [ 1.3177, -0.6248, -0.0692],
          [-0.3019,  0.7019,  0.4337],
          [-0.3266, -0.3216, -1.5235]],

         [[ 0.6664,  1.3566,  0.6241],
          [

torch.Size([4, 4, 3])

In [15]:
#take the mean across the color channels
torch.mean(t, axis=-1)

tensor([[[ 1.8621,  0.0661, -0.8397, -0.5086],
         [-0.2958,  0.2656, -0.2314,  0.0934],
         [ 0.7333,  0.3117,  1.4332,  0.7529],
         [ 0.1619,  0.1375, -0.3186,  0.3529]],

        [[ 0.2226, -0.5617,  0.0497,  0.5825],
         [-0.1253,  0.2079,  0.2779, -0.7239],
         [ 0.8824,  0.0039,  0.1214,  0.2672],
         [-0.2441,  0.8621,  0.9827,  0.0789]]])

In [16]:
torch.max(t, axis=-1)

torch.return_types.max(
values=tensor([[[ 3.0033,  0.9874,  0.0418,  0.4125],
         [-0.1110,  0.5552,  0.3217,  0.8903],
         [ 1.4867,  1.1714,  2.0522,  1.0669],
         [ 0.7036,  1.6389,  0.4060,  0.9432]],

        [[ 0.8024,  0.2586,  0.8494,  1.2909],
         [ 0.0095,  1.3177,  0.7019, -0.3216],
         [ 1.3566,  0.7033,  1.0865,  1.7342],
         [ 0.0206,  2.5815,  1.4025,  0.5641]]]),
indices=tensor([[[0, 1, 2, 1],
         [0, 0, 2, 1],
         [1, 0, 2, 0],
         [0, 2, 2, 1]],

        [[1, 2, 1, 1],
         [0, 0, 1, 1],
         [1, 0, 2, 2],
         [1, 1, 2, 0]]]))

### Gradients in PyTorch

In [17]:
x = torch.tensor([[5., 8.],[4., 6.]], requires_grad=True)
#store gradient after any operations
y = x.pow(3).sum() #operation
y

tensor(917., grad_fn=<SumBackward0>)

In [18]:
y.backward() #compute gradient
x.grad  #print the gradient (it is stored in x)

tensor([[ 75., 192.],
        [ 48., 108.]])

In [19]:
#check the result analitically
3*x**2

tensor([[ 75., 192.],
        [ 48., 108.]], grad_fn=<MulBackward0>)